### ISSUE TITLE
(Not working in Firefox, brave or safari) Feature Request: Port Selection

### ISSUE THREAD

**Issue by fsckyou** [mmiscool/serialTerminal.com#1]
It would be useful to select the serial port to use from a list or at a minimum enter the serial port in a text box.

**Comment by mmiscool** [comment]
Serial port selection is handled by the chrome browser API. When you click connect it will list devices and request you give permission to access.

**Comment by flywire** [comment]
> Serial Connection Failed

Running Win10 under Brave, Device on Com3

**Comment by mmiscool** [comment]
Brave decided not to implement this API @flywire 
Same with firefox. See the following links.
https://github.com/brave/brave-browser/issues/13902
https://mozilla.github.io/standards-positions/#webserial

**Comment by flywire** [comment]
Very disappointing. A scope comment should be included in readme that it is not currently supported in [Apple](https://webkit.org/tracking-prevention/) browsers, [Firefox](https://mozilla.github.io/standards-positions/#webserial) or [Brave](https://github.com/brave/brave-browser/issues/13902).
