### ISSUE TITLE
\r\n Would be nice to allow choice of either not both together

### ISSUE THREAD

**Issue by ghost** [mmiscool/serialTerminal.com#13]
please allow choice of sending with either \r or \n rather than both
in fact the ability to turn either on/off would cover the issue.

**Comment by Erbonator3000** [comment]
#15 PR pending

**Comment by mmiscool** [comment]
PR #15 has been approved.

**Comment by mmiscool** [comment]
@Erbonator3000 Thanks for making the changes.
