### ISSUE TITLE
Use with ESP32

### ISSUE THREAD

**Issue by happytm** [mmiscool/serialTerminal.com#2]
Do you think it will work with ESP32 webserver? Is it possible to display serial terminal of ESP32?

Thanks.

**Comment by mmiscool** [comment]
Yes. It has been reported to work with:
ESP32
ESP8266
Arduino
Duet2
the new raspberry pi microcontroler thing



Best thing you can do is give it a little test.

**Comment by happytm** [comment]
Thanks.
