### ISSUE TITLE
Eventually hangs unless the buffer gets cleared.

### ISSUE THREAD

**Issue by janbbeck** [mmiscool/serialTerminal.com#7]
After a few seconds of adding data to the window, it gets choppy, and eventually unresponsive altogether. This does not occur if I clear the window every few seconds.
I'm using Ubuntu 20.04 with Chrome Version 89.0.4389.114 (Official Build) (64-bit)

Maybe we can limit the data buffer size to make this stop?

**Comment by mmiscool** [comment]
Can you give me an approximate number of characters when you start to see the slowdown?

**Comment by janbbeck** [comment]
Sure. It starts happening around 45000 characters.
Also, while doing this experiment, I noticed that there was no disconnect or stop button. So I had to copy and paste the content fast, before the browser hangs. Maybe it's a good idea to add a stop button...

Thanks for serialterminal.com by the way!!

**Comment by mmiscool** [comment]
see if the fix I just did solved this issues. @janbbeck

**Comment by janbbeck** [comment]
Excellent! Fixed. Thank you.
